# fly.toml app configuration file generated for ptcg-pocket-bot on 2025-07-15T13:44:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ptcg-pocket-bot'
primary_region = 'hkg'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
